### ISSUE TITLE
Doesn't work. Error: Line 29, 69, 70: eslint: no-undef - 'MathJax' is not defined. 

### ISSUE THREAD

**Issue by rcswex** [scruel/tampermonkey-scripts#1]
Doesn't work. Error: Line 29, 69, 70: eslint: no-undef - 'MathJax' is not defined.

**Comment by scruel** [comment]
> Doesn't work. Error: Line 29, 69, 70: eslint: no-undef - 'MathJax' is not defined.

Please read README.md, it only works with browser plugin.
