### ISSUE TITLE
Doesn't work on bing chat

### ISSUE THREAD

**Issue by copiummax** [scruel/tampermonkey-scripts#10]
I am trying to make it work on bing but it simply doesn't work.

info:
- It loads mathjax successfully
- I tried refreshing and retrying multiple times

![lastprint](https://user-images.githubusercontent.com/104896334/225578672-7a23bc06-f698-47eb-97f8-b630b63ed6d8.png)
![image](https://user-images.githubusercontent.com/104896334/225579366-7aa26e61-bed6-46ae-9160-6d42258ec4dc.png)

**Comment by scruel** [comment]
Fixed in version 0.5.6, try again.
