### ISSUE TITLE
I get trouble in bing and chatgpt!!

### ISSUE THREAD

**Issue by luck7x** [scruel/tampermonkey-scripts#11]
![image](https://user-images.githubusercontent.com/122070731/229072553-789cf2f6-34ff-45ba-822a-b42a416b9da8.png)

**Comment by scruel** [comment]
Intersting...
不过看起来好像是 bing 本身输出的就有问题？ bing 不太容易复现问题，贴 chatgpt 吧。

**Comment by luck7x** [comment]
那我应该怎么做呢，告诉他输出需要带$符号吗？

--------------原始邮件--------------
发件人："Scruel&nbsp;Tao ***@***.***&gt;;
发送时间：2023年3月31日(星期五) 下午4:49
收件人："scruel/tampermonkey-scripts" ***@***.***&gt;;
抄送："刘宇轩 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [scruel/tampermonkey-scripts] I get trouble in bing and chatgpt!! (Issue #11)
-----------------------------------

 

 
Intersting...
 不过看起来好像是 bing 本身输出的就有问题？

**Comment by scruel** [comment]
> 那我应该怎么做呢，告诉他输出需要带$符号吗？

可以试试，但 bing 比较难复现，没法确认问题。
如果 chatgpt有问题，可以把插件关了后刷新，把原文以代码形式贴到这里来
