### ISSUE TITLE
Italic formatting in non-formula part loses characters

### ISSUE THREAD

**Issue by lethefrost** [scruel/tampermonkey-scripts#13]
Hi scruel 😊 I start this new thread here for the issue in v0.5.8. Please see the screenshots below:

|Case|Originally|With your script|Result|
|--:|:--:|:--:|:--|
|italic word `wind`|<img width="674" alt="image" src="https://user-images.githubusercontent.com/47198693/230745274-9f5f9f48-1275-409a-addb-8a7316142fb6.png">|<img width="638" alt="image" src="https://user-images.githubusercontent.com/47198693/230745559-62be555f-fdf0-4f46-be56-f769b8cddfb5.png">|the whole word lost
|italic word `Italy`|<img width="661" alt="image" src="https://user-images.githubusercontent.com/47198693/230745343-310ff352-a447-4bc3-babb-ab631ffae056.png">|<img width="652" alt="image" src="https://user-images.githubusercontent.com/47198693/230745537-ef205996-2441-4e7d-9972-d8dd6010f446.png">|the last character lost
|italicized full sentences|<img width="675" alt="image" src="https://user-images.githubusercontent.com/47198693/230745392-ba7e491c-5b07-4e8b-98b4-7ba1ba5cc68c.png">|<img width="642" alt="image" src="https://user-images.githubusercontent.com/47198693/230745448-716f16b2-2f99-490e-8ef1-e5204d39e3e4.png">| indefinite numbers of leading/trailing characters lost

**Comment by scruel** [comment]
Can you also include your input in the screenshot? thanks.

**Comment by lethefrost** [comment]
> Can you also include your input in the screenshot? thanks.

Just like in the cell at the top left, I prompt it to generate some random italicized contents.

**Comment by scruel** [comment]
> > Can you also include your input in the screenshot? thanks.
> 
> Just like in the cell at the top left, I prompt it to generate some random italicized contents.

Ok, reproduced, checking.

**Comment by scruel** [comment]
Fixed in 0.5.9
