### ISSUE TITLE
重新生成回答会将公式均无法显示或错误显示

### ISSUE THREAD

**Issue by jay2640** [scruel/tampermonkey-scripts#14]
多个答案页面公式不显示以及显示错误，例如
![image](https://user-images.githubusercontent.com/43470722/232429323-c1b79969-18f2-4864-8b9e-14214a4d5293.png)
![image](https://user-images.githubusercontent.com/43470722/232429425-42baf07a-b3bc-45a8-a4eb-854519dd8a94.png)

**Comment by scruel** [comment]
检查下是不是最新 0.6.2 版本，如果不是，请更新。
如果是的话，可以先检查下是否是与其他插件冲突了。
排查问题需要你提供下原始 prompt，我这里尝试了下图中的第一句，初次生成和重新生成都是没什么问题的：
![img](https://user-images.githubusercontent.com/16933298/232439141-be7c9a7b-97af-423f-902a-47cc1dee589d.png)

**Comment by scruel** [comment]
好像复现了，你是不是指点击左右之后，不会渲染的问题？这个确实是一直都没有支持，毕竟一般都是看最后一个，我有空补一下吧。

**Comment by scruel** [comment]
Fixed

**Comment by mnixry** [comment]
![image](https://user-images.githubusercontent.com/32300164/233543824-4f33ee83-0151-41ce-a68a-c160169bca66.png)


> 好像复现了，你是不是指点击左右之后，不会渲染的问题？这个确实是一直都没有支持，毕竟一般都是看最后一个，我有空补一下吧。

您好，我遇到了同样的问题，是最新的 `0.6.3` 版本脚本

**Comment by scruel** [comment]
@mnixry 修复了，openai 也在更新前端，他又加了个按钮影响了脚本的判断逻辑（
