### ISSUE TITLE
Residual XXXSCUEDLXXX and XXXSCAESKXXX in rendering results

### ISSUE THREAD

**Issue by lethefrost** [scruel/tampermonkey-scripts#16]
Hi scruel, I understand this might be the current solution for the latex-markdown rendering order issue we discussed a little while ago at #12 . Looks like you are substituting `_` with `XXXSCUEDLXXX`, and `*` with `XXXSCAESKXXX` in the GPT generated contents. However, there might be a bug. I have been seeing `XXXSCUEDLXXX` and `XXXSCAESKXXX` everywhere in the rendered ChatGPT's answers, in plain text, italic/ bold text, code block/ inline code... Could this be possibly caused by failing to replace the `_` and `*`s back afterward?

<img width="717" alt="image" src="https://user-images.githubusercontent.com/47198693/233797932-87286aab-ccc6-4bd5-b262-2a4597c27094.png">
<img width="690" alt="image" src="https://user-images.githubusercontent.com/47198693/233797959-96294849-d583-4fe9-a169-cb8a6da4eb08.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/47198693/233797969-9cd9410d-83a4-4e1d-bb87-3996f73007da.png">

**Comment by scruel** [comment]
It might be related to a force push I made which contains a typo, try 0.6.4.

**Comment by scruel** [comment]
Fixed, caused by the update by OpenAI.

**Comment by lethefrost** [comment]
> It might be related to a force push I made which contains a typo, try 0.6.4.

I just updated to 0.6.4 but this problem still exists.

By the way, I further find that even though refreshing the page might sometimes fix the rendered results, the code copied from code blocks still contains the placeholders in it.

**Comment by scruel** [comment]
> > It might be related to a force push I made which contains a typo, try 0.6.4.
> 
> I just updated to 0.6.4 but this problem still exists.
> 
> By the way, I further find that even though refreshing the page might sometimes fix the rendered results, the code copied from code blocks still contains the placeholders in it.

Yeah, I just released 0.6.5

**Comment by lethefrost** [comment]
> > > It might be related to a force push I made which contains a typo, try 0.6.4.
> > 
> > 
> > I just updated to 0.6.4 but this problem still exists.
> > By the way, I further find that even though refreshing the page might sometimes fix the rendered results, the code copied from code blocks still contains the placeholders in it.
> 
> Yeah, I just released 0.6.5

The problems are still here for me in 0.6.5 (for both rendered and copied contents)

**Comment by scruel** [comment]
Really? For copy, it's another issue, lets keep it in another issue, but for rendering, I think I already solved, screenshot please?

**Comment by scruel** [comment]
@lethefrost For copy, fixed, try 0.6.6.

**Comment by lethefrost** [comment]
> Really? For copy, it's another issue, lets keep it in another issue, but for rendering, I think I already solved, screenshot please?

sure, with 0.6.5, this is the screeshot:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/47198693/233801542-c1ae2194-bcf5-49eb-8774-a539be0f2775.png">

**Comment by scruel** [comment]
@lethefrost 
![2023-04-23_02-57-19](https://user-images.githubusercontent.com/16933298/233801829-60d34401-9830-4dff-8867-47087d5a16d9.png)

Can't reproduce it in my side?

**Comment by scruel** [comment]
@lethefrost
Ok, reproduced it on FireFox, let me check then, for Edge, it works fine.

**Comment by scruel** [comment]
@lethefrost I can only reproduced it while switching the conversations, it will be fixed later, can you be sure that you are using the lastest version? Try refresh the page and check again?

**Comment by lethefrost** [comment]
> @lethefrost I can only reproduced it while switching the conversations, it will be fixed later, can you be sure that you are using the lastest version? Try refresh the page and check again?

Hi, I updated to 0.6.7 and seems like it is fixed! Both the rendering and copying issues. Thank you so much! Very nice work.
