### ISSUE TITLE
出现XXXSCUEDLXXX乱码

### ISSUE THREAD

**Issue by Bright-Nabarro** [scruel/tampermonkey-scripts#18]
在代码中经常出现XXXSCUEDLXXX
问题: 举个使用binary_function的例子
好像代码中用到下划线和*字符的地方就会出现这个字符
![1](https://user-images.githubusercontent.com/59719030/236813289-1ec09d83-e52d-4641-bba7-c2ef962670b5.png)
![image](https://user-images.githubusercontent.com/59719030/236813371-7677e495-5eac-4328-bd6f-c402caca84b3.png)

**Comment by scruel** [comment]
如果只是出现，那是正常的，这是为了解决 #12 的问题，但占位符会在出现之后，很快重新变回原本的字符。
如果一段时间还没有变，那说明不正常，我尝试了你的 prompt，但并未能够复现问题。
你可以仔细回忆一下之前是不是做了什么特殊操作，比如切换会话之类，让我这边能复现问题我才能解决，或者有没有可能是其他插件冲突，以及请确保用的版本是最新的。

**Comment by scruel** [comment]
我这里刚才倒是发现了一个能复现该问题的步骤：
先创建一个将会包含 `_` 符号的会话，然后点击新建会话，再切回去，占位符还会保留

这个我会着手处理一下，其他的暂时没有发现

**Comment by scruel** [comment]
> 我这里刚才倒是发现了一个能复现该问题的步骤： 先创建一个将会包含 `_` 符号的会话，然后点击新建会话，再切回去，占位符还会保留
> 
> 这个我会着手处理一下，其他的暂时没有发现

Fixed in v0.6.9
