### ISSUE TITLE
Does not activate in the browser plug-in.

### ISSUE THREAD

**Issue by rcswex** [scruel/tampermonkey-scripts#2]
<img width="960" alt="tp1" src="https://user-images.githubusercontent.com/61713868/219268434-a1b1f348-e226-453b-b300-5342df9865b9.png">

![tp2](https://user-images.githubusercontent.com/61713868/219268441-036670d8-a423-4442-8ead-1e9e4143dfd6.png)

![tp3](https://user-images.githubusercontent.com/61713868/219268454-f427b2a1-07f9-4d83-b5e2-26d35eae2e67.png)

“没有运行中的脚本”

**Comment by scruel** [comment]
修好了，更新一下版本到 0.3.7
