### ISSUE TITLE
公式渲染错误XXXSCUEDLXXX

### ISSUE THREAD

**Issue by Book-fall2wish** [scruel/tampermonkey-scripts#20]
开启脚本
![QQ截图20230914114523](https://github.com/scruel/tampermonkey-scripts/assets/13326189/2f11fffa-0e7b-41ba-bda1-0fb3a8e1f52e)
![QQ截图20230914114757](https://github.com/scruel/tampermonkey-scripts/assets/13326189/350401b9-3fbc-4bd4-8aa7-8a565c9b2c7d)
日志如下：
[开脚本时控制台.txt](https://github.com/scruel/tampermonkey-scripts/files/12604568/default.txt)

关闭脚本
![QQ截图20230914115112](https://github.com/scruel/tampermonkey-scripts/assets/13326189/6a992483-940f-4cec-beba-29d0c38786d8)
![QQ截图20230914115028](https://github.com/scruel/tampermonkey-scripts/assets/13326189/4acb2072-7f6a-414d-8962-9f94861ba017)
日志如下：
[关脚本时控制台.txt](https://github.com/scruel/tampermonkey-scripts/files/12604559/default.txt)

**Comment by Book-fall2wish** [comment]
Microsoft Edge
版本 118.0.2088.2 (正式版本) dev (64 位)

Firefox
117.0.1 (64 位)

以上两个浏览器均可复现

**Comment by scruel** [comment]
有段时间没在用了，我这周双休修一下

**Comment by scruel** [comment]
有段时间没在用了，我这周休息时修一下，能否分享一下 ChatGPT 的网页链接？

**Comment by Book-fall2wish** [comment]
https://chat.openai.com/share/9ddeb5c4-5334-48bb-8a85-3bf0d6c5e39a
是这个意思吗？

**Comment by scruel** [comment]
是的，我这边回头修一下
