### ISSUE TITLE
chatGPT 中存在会导致页面卡顿的问题

### ISSUE THREAD

**Issue by duanzheng** [scruel/tampermonkey-scripts#3]
当页面已经 ready 之后由于每一秒钟都会触发 MathJax.typeset(); 会导致页面重排而卡顿，并且里面可能还存在内存泄漏最终会导致页面卡死崩溃。

**Comment by scruel** [comment]
已经有个todo了，后面只会解析最后一个会话元素，空了就更新，有兴趣你也可以pr

**Comment by duanzheng** [comment]
> 已经有个todo了，后面只会解析最后一个会话元素，空了就更新，有兴趣你也可以pr

我不太了解MathJax库的使用方式，你这个办法不错，或者可能有个简单的办法是通过MutationObserver监听输入框的变化，只有从loading恢复为默认状态才触发一次

**Comment by scruel** [comment]
> > 已经有个todo了，后面只会解析最后一个会话元素，空了就更新，有兴趣你也可以pr
> 
> 我不太了解MathJax库的使用方式，你这个办法不错，或者可能有个简单的办法是通过MutationObserver监听输入框的变化，只有从loading恢复为默认状态才触发一次

上面提到的方案考虑的不全面，比如会有历史会话的公式解析等问题。
卡顿大概率是同时刻大量重复公式需要解析导致的，现在更新了一下，可以试试看，有问题再联系。

**Comment by scruel** [comment]
> 我不太了解MathJax库的使用方式，你这个办法不错，或者可能有个简单的办法是通过MutationObserver监听输入框的变化，只有从loading恢复为默认状态才触发一次

昨天研究了一下 MutationObserver，发现确实可以替代掉循环检查，花了点时间做重新适配和版本更新，谢谢提供建议。
如果新版本有啥问题，欢迎提交新 issue。
Have fun~
