### ISSUE TITLE
There is a bug!

### ISSUE THREAD

**Issue by junqi1121** [scruel/tampermonkey-scripts#5]
Dear author, there seems to be a problem with the rendering of the script when these formulas appear on the page.
![image](https://user-images.githubusercontent.com/90767596/222390276-d2e0e16f-aa05-4f5a-95b2-b544f187cf28.png)

**Comment by scruel** [comment]
If ChatGPT won't wrapper the latex formulas within symbol `$`, the script won't typeset them.
So, you should report this issue to OpenAI, rather than this repo ^_^.
