### ISSUE TITLE
大佬可以匹配手机版firefox吗？

### ISSUE THREAD

**Issue by love2046** [scruel/tampermonkey-scripts#7]
rt

**Comment by scruel** [comment]
上图看下实际情况吧，或者描述下目前有什么问题

**Comment by love2046** [comment]
![Screenshot_2023-03-08-16-45-02-13_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/65494499/223665623-9a979312-37d0-4e97-8726-267f63fbc08d.jpg)
![Screenshot_2023-03-08-16-44-06-39_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/65494499/223665661-011a36fa-fdd8-4409-a066-2b118b3847ac.jpg)
用了这个插件在浏览器中没反应

**Comment by scruel** [comment]
好的，空了我再看下吧

**Comment by love2046** [comment]
![Screenshot_2023-03-08-16-43-44-09_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/65494499/223666560-62383565-0335-456f-945f-04d3f396816c.jpg)
上面图少了一个，chatgpt页面是这样的

**Comment by scruel** [comment]
其实手机支持还有点麻烦，界面小就容易溢出，等我抽时间把 #6 移植了，再来看这个问题吧。

**Comment by love2046** [comment]
大佬，我把firefox改成“桌面版网站”时
![IMG_20230308_215237](https://user-images.githubusercontent.com/65494499/223730893-6655494a-6e6b-41e7-a4c9-a7633194cc3f.jpg)
页面这变成这样了，前面一个回答本来是渲染好的了，页面往下一拉，再回去，又变成原始公式里
如图
![Screenshot_2023-03-08-21-49-42-47](https://user-images.githubusercontent.com/65494499/223731285-27bc431d-76a5-42e8-a31f-327203b7957f.jpg)

**Comment by love2046** [comment]
再chatgpt帮助下，把
window.setTimeout(resolver, 500);
改成
window.setTimeout(resolver, 2000);
可以完美显示公式了
![Screenshot_2023-03-09-07-32-08-93_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/65494499/223876932-c9929a73-294a-4c91-a179-f8650a03dd2b.jpg)

**Comment by scruel** [comment]
> 再chatgpt帮助下，把 window.setTimeout(resolver, 500); 改成 window.setTimeout(resolver, 2000); 

欸？为什么要改这句呢，改成桌面网站能用的话，应该是手机版元素信息不一致，不过先能用就行吧~
