### ISSUE TITLE
关于在New Bing和You.com不可用的问题

### ISSUE THREAD

**Issue by itworksig** [scruel/tampermonkey-scripts#8]
续 [感谢作者！ 但是它在New Bing和You.com不解析Latex](https://greasyfork.org/zh-CN/scripts/456049-chatgpt-latex-auto-render-openai-you-new-bing-etc/discussions/172349)

浏览器: Chrome Version 109.0.5414.119 (Official Build) (arm64)
OS: MacOS Ventura
ChatGPT LaTeX Auto Render版本:  [v0.5.4](https://greasyfork.org/zh-CN/scripts/456049-chatgpt-latex-auto-render-openai-you-new-bing-etc?version=1159118)

### 在ChatGPT正常
<img width="918" alt="image" src="https://user-images.githubusercontent.com/119853210/224116331-d56e93de-fc9a-4d5d-8f89-7449235f61e3.png">

### 在New Bing不正常
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/119853210/224116660-928dc3ea-eebe-4b3a-aef3-9e20bd329c3c.png">

### 在You.com不正常
<img width="890" alt="image" src="https://user-images.githubusercontent.com/119853210/224116913-9d5341db-2669-4a03-bf8c-a5b63b21c7d7.png">

**Comment by itworksig** [comment]
在Edge下，问题同样存在

<img width="1516" alt="image" src="https://user-images.githubusercontent.com/119853210/224120007-d08039f4-ae5f-4485-9a93-118fac8f3d1d.png">

**Comment by scruel** [comment]
在代码块中的是不会解析的，要让他直接输出来，而不是放在代码块中。

**Comment by scruel** [comment]
在 Chrome 上测试了一下：
you 不解析原因是 CSP 策略导致的，Chrome 对于 CSP 策略遵守较为严格，尝试了下暂时没有啥办法绕过，不过测试过 edge 和 firefox 没有这个问题，有需要使用的话建议更换后尝试。（https://github.com/Tampermonkey/tampermonkey/issues/1733）
bing 我这边测试是没问题的，图片中不解析的原因，是输出的时候把公式放在代码块中了，代码块的中内容是不会解析的。

补充：如果一定要使用 Chrome，可以在 tampermonkey 设置的 Security 设置组中，修改选项移除页面的 CSP 规则（不安全）。

**Comment by lisonge** [comment]
> 尝试了下暂时没有啥办法绕过

将远程代码通过 `@require` 加载不行吗？

```js
// ==UserScript==
// @require     https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
// ==/UserScript==

console.log(window.MathJax);
// {version: '3.2.2', _: {…}, config: {…}, loader: {…}, startup: {…}, …}
```
