### ISSUE TITLE
Bold display is not supported.

### ISSUE THREAD

**Issue by zzyjay** [scruel/tampermonkey-scripts#9]
Bold symbole display is not supported.
code`\boldsymbol` is shown in chatgpt

**Comment by scruel** [comment]
> Bold symbole display is not supported. code`\boldsymbol` is shown in chatgpt

Could you provide more details such like screenshots which included your screen and console log output?

**Comment by zzyjay** [comment]
![image](https://user-images.githubusercontent.com/60791309/225280662-d5783ae9-bf5c-4470-b9bf-fdb0ea641278.jpeg)
Device：ipad pro
browser：safari 

BTW：Thank you very much for your project, which has greatly improved my experience.

**Comment by scruel** [comment]
> Device：ipad pro browser：safari
> 
> BTW：Thank you very much for your project, which has greatly improved my experience.

Could you turn off the script, then copy the whole content and paste it here?

I'm glad to hear that you think this little script is helpful~
